apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mroludev/mysql.git # insert the git repo, the only source of truth, must be same with the secret yaml file
    targetRevision: main
    path: mysql           # the folder in the repo that contains the manifests
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql # the app namespace

  syncPolicy:
    automated: {}
 