# apiVersion: v1
# kind: Secret
# metadata:
#   name: micros-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   type: git
#   url: https://github.com/mroludev/micros.git # repo url
#   password: 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   # create a login token from github
#   username: mroludev
---
apiVersion: v1
kind: Secret
metadata:
  name: micros-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/mroludev/micros.git # repo url
  password: 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   # create a login token from github
  username: mroludev